# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_Graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_graph(object):
    def setupUi(self, New_graph):
        New_graph.setObjectName("New_graph")
        New_graph.resize(874, 700)
        self.table_values = QtWidgets.QTableWidget(New_graph)
        self.table_values.setGeometry(QtCore.QRect(10, 20, 301, 621))
        self.table_values.setObjectName("table_values")
        self.table_values.setColumnCount(0)
        self.table_values.setRowCount(0)
        self.label = QtWidgets.QLabel(New_graph)
        self.label.setGeometry(QtCore.QRect(480, 60, 61, 31))
        self.label.setObjectName("label")
        self.line_name = QtWidgets.QLineEdit(New_graph)
        self.line_name.setGeometry(QtCore.QRect(550, 60, 171, 31))
        self.line_name.setObjectName("line_name")
        self.line_x_name = QtWidgets.QLineEdit(New_graph)
        self.line_x_name.setGeometry(QtCore.QRect(550, 120, 171, 31))
        self.line_x_name.setObjectName("line_x_name")
        self.line_y_name = QtWidgets.QLineEdit(New_graph)
        self.line_y_name.setGeometry(QtCore.QRect(552, 181, 171, 31))
        self.line_y_name.setObjectName("line_y_name")
        self.label_2 = QtWidgets.QLabel(New_graph)
        self.label_2.setGeometry(QtCore.QRect(490, 180, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(New_graph)
        self.label_3.setGeometry(QtCore.QRect(490, 120, 61, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(New_graph)
        self.label_4.setGeometry(QtCore.QRect(330, 240, 211, 31))
        self.label_4.setObjectName("label_4")
        self.line_x_error = QtWidgets.QLineEdit(New_graph)
        self.line_x_error.setGeometry(QtCore.QRect(550, 240, 171, 31))
        self.line_x_error.setObjectName("line_x_error")
        self.line_y_error = QtWidgets.QLineEdit(New_graph)
        self.line_y_error.setGeometry(QtCore.QRect(550, 290, 171, 31))
        self.line_y_error.setObjectName("line_y_error")
        self.label_5 = QtWidgets.QLabel(New_graph)
        self.label_5.setGeometry(QtCore.QRect(330, 290, 211, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(New_graph)
        self.label_6.setGeometry(QtCore.QRect(330, 330, 541, 20))
        self.label_6.setObjectName("label_6")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(New_graph)
        self.buttonBox_2.setGeometry(QtCore.QRect(500, 400, 193, 28))
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")

        self.retranslateUi(New_graph)
        self.buttonBox_2.accepted.connect(New_graph.accept)
        self.buttonBox_2.rejected.connect(New_graph.reject)
        QtCore.QMetaObject.connectSlotsByName(New_graph)

    def retranslateUi(self, New_graph):
        _translate = QtCore.QCoreApplication.translate
        New_graph.setWindowTitle(_translate("New_graph", "Dialog"))
        self.label.setText(_translate("New_graph", "Название:"))
        self.label_2.setText(_translate("New_graph", "Ось Y:"))
        self.label_3.setText(_translate("New_graph", "Ось Х:"))
        self.label_4.setText(_translate("New_graph", "Универсальная погрешность по X:"))
        self.label_5.setText(_translate("New_graph", "Универсальная погрешность по Y:"))
        self.label_6.setText(_translate("New_graph", "(Универсальная погрешность пишется только если столбцы погрешностей X и Y пустые)"))
