# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Transit_graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 442)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 380, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listWidget_all_graphs = QtWidgets.QListWidget(Dialog)
        self.listWidget_all_graphs.setGeometry(QtCore.QRect(0, 10, 221, 401))
        self.listWidget_all_graphs.setObjectName("listWidget_all_graphs")
        self.checkBox_approk_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_approk_2.setGeometry(QtCore.QRect(240, 10, 141, 20))
        self.checkBox_approk_2.setObjectName("checkBox_approk_2")
        self.checkBox_differ_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_differ_2.setGeometry(QtCore.QRect(240, 50, 211, 20))
        self.checkBox_differ_2.setObjectName("checkBox_differ_2")
        self.checkBox_integer_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_integer_2.setGeometry(QtCore.QRect(240, 90, 141, 20))
        self.checkBox_integer_2.setObjectName("checkBox_integer_2")
        self.checkBox_points = QtWidgets.QCheckBox(Dialog)
        self.checkBox_points.setGeometry(QtCore.QRect(240, 130, 121, 20))
        self.checkBox_points.setObjectName("checkBox_points")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_approk_2.setText(_translate("Dialog", "Аппроксимировать"))
        self.checkBox_differ_2.setText(_translate("Dialog", "Дифференцировать"))
        self.checkBox_integer_2.setText(_translate("Dialog", "Интегрировать"))
        self.checkBox_points.setText(_translate("Dialog", "Только точки "))
